## Data Audits

In [5]:
import pandas as pd # type: ignore
data_audit = pd.read_csv("../data/zepto_v1.csv")

print("--- SHAPE ---")
print(data_audit.shape)

--- SHAPE ---
(3732, 9)

In [12]:
print("--- COLUMNS ---")
print(data_audit.columns.tolist())

--- COLUMNS ---
['Category', 'name', 'mrp', 'discountPercent', 'availableQuantity', 'discountedSellingPrice', 'weightInGms', 'outOfStock', 'quantity']

In [23]:
print("--- DATA TYPES ---")
print(data_audit.dtypes)

--- DATA TYPES ---
Category                    str
name                        str
mrp                       int64
discountPercent           int64
availableQuantity         int64
discountedSellingPrice    int64
weightInGms               int64
outOfStock                 bool
quantity                  int64
dtype: object

In [18]:
print("--- FRIST 5 ROWS ---")
data_audit.head()

--- FRIST 5 ROWS ---

,Category,name,mrp,discountPercent,availableQuantity,discountedSellingPrice,weightInGms,outOfStock,quantity
0,Fruits & Vegetables,Onion,2500,16,3,2100,1000,False,1
1,Fruits & Vegetables,Tomato Hybrid,4200,16,3,3500,1000,False,1
2,Fruits & Vegetables,Tender Coconut,5100,15,3,4300,58,False,1
3,Fruits & Vegetables,Coriander Leaves,2000,15,3,1700,100,False,100
4,Fruits & Vegetables,Ladies Finger,1400,14,3,1200,250,False,250

In [33]:
print("--- MISSING VALUES ---")
print(data_audit.isnull().sum())

--- MISSING VALUES ---
Category                  0
name                      0
mrp                       0
discountPercent           0
availableQuantity         0
discountedSellingPrice    0
weightInGms               0
outOfStock                0
quantity                  0
dtype: int64

In [36]:
print("--- DUPLICATES ---")
print("Duplicate rows:", data_audit.duplicated().sum())

--- DUPLICATES ---
Duplicate rows: 2

In [39]:
print("\n--- SUMMARY ---")
data_audit.describe(include="all")

--- SUMMARY ---

,Category,name,mrp,discountPercent,availableQuantity,discountedSellingPrice,weightInGms,outOfStock,quantity
count,3732,3732,3732.000000,3732.000000,3732.000000,3732.000000,3732.000000,3732,3732.000000
unique,14,1681,NaN,NaN,NaN,NaN,NaN,2,NaN
top,Cooking Essentials,Arden Eggs White,NaN,NaN,NaN,NaN,NaN,False,NaN
freq,514,10,NaN,NaN,NaN,NaN,NaN,3279,NaN
mean,NaN,NaN,15680.117899,7.617095,4.008574,14192.834941,387.843783,NaN,213.270900
std,NaN,NaN,16088.807618,9.211733,2.203511,13850.726265,678.096509,NaN,194.730976
min,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
25%,NaN,NaN,6000.000000,0.000000,2.000000,5500.000000,100.000000,NaN,50.000000
50%,NaN,NaN,11000.000000,6.000000,5.000000,10400.000000,225.000000,NaN,186.000000
75%,NaN,NaN,20000.000000,10.000000,6.000000,18400.000000,450.000000,NaN,340.000000
max,NaN,NaN,260000.000000,51.000000,6.000000,139900.000000,10000.000000,NaN,1500.000000